apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgeops-api
  namespace: edgeops
  labels:
    app: edgeops-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: edgeops-api
  template:
    metadata:
      labels:
        app: edgeops-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: MONGO_URI
              value: mongodb://edgeops-mongodb:27017
            - name: MONGO_DB
              value: edgeops
            - name: KAFKA_BOOTSTRAP
              value: edgeops-kafka:9092
            - name: REDIS_URL
              value: redis://edgeops-redis:6379
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
---
apiVersion: v1
kind: Service
metadata:
  name: edgeops-api
  namespace: edgeops
spec:
  selector:
    app: edgeops-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
