apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edgeops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/samapika99/edgeops-onprem-devops-platform.git
    targetRevision: main
    path: helm/edgeops
  destination:
    server: https://kubernetes.default.svc
    namespace: edgeops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
